language: node_js
node_js: '8.12'
cache:
  directories:
    - platforms
    - plugins
before_script: npm install -g ionic@3.18.0 cordova@8.0
script:
  - echo "Building app"
  - export NODE_ENV=prod; gulp
  - ionic cordova platform add browser --no-interactive; ionic cordova build browser --prod --no-interactive
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local_dir: www
  on:
    branch: master
